/// Border map generated from REST Countries (`cca2`, `cca3`, `borders`).
///
/// Source used on 2026-04-26:
/// https://restcountries.com/v3.1/all?fields=cca2,cca3,borders
const Map<String, List<String>> countryBorders = {
  'AD': ['FR', 'ES'],
  'AE': ['OM', 'SA'],
  'AF': ['IR', 'PK', 'TM', 'UZ', 'TJ', 'CN'],
  'AL': ['ME', 'GR', 'MK', 'XK'],
  'AM': ['AZ', 'GE', 'IR', 'TR'],
  'AO': ['CG', 'CD', 'ZM', 'NA'],
  'AR': ['BO', 'BR', 'CL', 'PY', 'UY'],
  'AT': ['CZ', 'DE', 'HU', 'IT', 'LI', 'SK', 'SI', 'CH'],
  'AZ': ['AM', 'GE', 'IR', 'RU', 'TR'],
  'BA': ['HR', 'ME', 'RS'],
  'BD': ['MM', 'IN'],
  'BE': ['FR', 'DE', 'LU', 'NL'],
  'BF': ['BJ', 'CI', 'GH', 'ML', 'NE', 'TG'],
  'BG': ['GR', 'MK', 'RO', 'RS', 'TR'],
  'BI': ['CD', 'RW', 'TZ'],
  'BJ': ['BF', 'NE', 'NG', 'TG'],
  'BN': ['MY'],
  'BO': ['AR', 'BR', 'CL', 'PY', 'PE'],
  'BR': ['AR', 'BO', 'CO', 'GF', 'GY', 'PY', 'PE', 'SR', 'UY', 'VE'],
  'BT': ['CN', 'IN'],
  'BW': ['NA', 'ZA', 'ZM', 'ZW'],
  'BY': ['LV', 'LT', 'PL', 'RU', 'UA'],
  'BZ': ['GT', 'MX'],
  'CA': ['US'],
  'CD': ['AO', 'BI', 'CF', 'CG', 'RW', 'SS', 'TZ', 'UG', 'ZM'],
  'CF': ['CM', 'TD', 'CD', 'CG', 'SS', 'SD'],
  'CG': ['AO', 'CM', 'CF', 'CD', 'GA'],
  'CH': ['AT', 'FR', 'IT', 'LI', 'DE'],
  'CI': ['BF', 'GH', 'GN', 'LR', 'ML'],
  'CL': ['AR', 'BO', 'PE'],
  'CM': ['CF', 'TD', 'CG', 'GQ', 'GA', 'NG'],
  'CN': ['AF', 'BT', 'MM', 'HK', 'IN', 'KZ', 'NP', 'KP', 'KG', 'LA', 'MO', 'MN', 'PK', 'RU', 'TJ', 'VN'],
  'CO': ['BR', 'EC', 'PA', 'PE', 'VE'],
  'CR': ['NI', 'PA'],
  'CZ': ['AT', 'DE', 'PL', 'SK'],
  'DE': ['AT', 'BE', 'CZ', 'DK', 'FR', 'LU', 'NL', 'PL', 'CH'],
  'DJ': ['ER', 'ET', 'SO'],
  'DK': ['DE'],
  'DO': ['HT'],
  'DZ': ['TN', 'LY', 'NE', 'EH', 'MR', 'ML', 'MA'],
  'EC': ['CO', 'PE'],
  'EE': ['LV', 'RU'],
  'EG': ['IL', 'LY', 'PS', 'SD'],
  'EH': ['DZ', 'MR', 'MA'],
  'ER': ['DJ', 'ET', 'SD'],
  'ES': ['AD', 'FR', 'GI', 'PT', 'MA'],
  'ET': ['DJ', 'ER', 'KE', 'SO', 'SS', 'SD'],
  'FI': ['NO', 'SE', 'RU'],
  'FR': ['AD', 'BE', 'DE', 'IT', 'LU', 'MC', 'ES', 'CH'],
  'GA': ['CM', 'CG', 'GQ'],
  'GB': ['IE'],
  'GE': ['AM', 'AZ', 'RU', 'TR'],
  'GF': ['BR', 'SR'],
  'GH': ['BF', 'CI', 'TG'],
  'GI': ['ES'],
  'GM': ['SN'],
  'GN': ['CI', 'GW', 'LR', 'ML', 'SN', 'SL'],
  'GQ': ['CM', 'GA'],
  'GR': ['AL', 'BG', 'TR', 'MK'],
  'GT': ['BZ', 'SV', 'HN', 'MX'],
  'GW': ['GN', 'SN'],
  'GY': ['BR', 'SR', 'VE'],
  'HK': ['CN'],
  'HN': ['GT', 'SV', 'NI'],
  'HR': ['BA', 'HU', 'ME', 'RS', 'SI'],
  'HT': ['DO'],
  'HU': ['AT', 'HR', 'RO', 'RS', 'SK', 'SI', 'UA'],
  'ID': ['TL', 'MY', 'PG'],
  'IE': ['GB'],
  'IL': ['EG', 'JO', 'LB', 'PS', 'SY'],
  'IN': ['BD', 'BT', 'MM', 'CN', 'NP', 'PK'],
  'IQ': ['IR', 'JO', 'KW', 'SA', 'SY', 'TR'],
  'IR': ['AF', 'AM', 'AZ', 'IQ', 'PK', 'TR', 'TM'],
  'IT': ['AT', 'FR', 'SM', 'SI', 'CH', 'VA'],
  'JO': ['IQ', 'IL', 'PS', 'SA', 'SY'],
  'KE': ['ET', 'SO', 'SS', 'TZ', 'UG'],
  'KG': ['CN', 'KZ', 'TJ', 'UZ'],
  'KH': ['LA', 'TH', 'VN'],
  'KP': ['CN', 'KR', 'RU'],
  'KR': ['KP'],
  'KW': ['IQ', 'SA'],
  'KZ': ['CN', 'KG', 'RU', 'TM', 'UZ'],
  'LA': ['MM', 'KH', 'CN', 'TH', 'VN'],
  'LB': ['IL', 'SY'],
  'LI': ['AT', 'CH'],
  'LR': ['GN', 'CI', 'SL'],
  'LS': ['ZA'],
  'LT': ['BY', 'LV', 'PL', 'RU'],
  'LU': ['BE', 'FR', 'DE'],
  'LV': ['BY', 'EE', 'LT', 'RU'],
  'LY': ['DZ', 'TD', 'EG', 'NE', 'SD', 'TN'],
  'MA': ['DZ', 'EH', 'ES'],
  'MC': ['FR'],
  'MD': ['RO', 'UA'],
  'ME': ['AL', 'BA', 'HR', 'XK', 'RS'],
  'MF': ['SX'],
  'MK': ['AL', 'BG', 'GR', 'XK', 'RS'],
  'ML': ['DZ', 'BF', 'GN', 'CI', 'MR', 'NE', 'SN'],
  'MM': ['BD', 'CN', 'IN', 'LA', 'TH'],
  'MN': ['CN', 'RU'],
  'MO': ['CN'],
  'MR': ['DZ', 'ML', 'SN', 'EH'],
  'MW': ['MZ', 'TZ', 'ZM'],
  'MX': ['BZ', 'GT', 'US'],
  'MY': ['BN', 'ID', 'TH'],
  'MZ': ['MW', 'ZA', 'SZ', 'TZ', 'ZM', 'ZW'],
  'NA': ['AO', 'BW', 'ZA', 'ZM'],
  'NE': ['DZ', 'BJ', 'BF', 'TD', 'LY', 'ML', 'NG'],
  'NG': ['BJ', 'CM', 'TD', 'NE'],
  'NI': ['CR', 'HN'],
  'NL': ['BE', 'DE'],
  'NO': ['FI', 'SE', 'RU'],
  'NP': ['CN', 'IN'],
  'OM': ['SA', 'AE', 'YE'],
  'PA': ['CO', 'CR'],
  'PE': ['BO', 'BR', 'CL', 'CO', 'EC'],
  'PG': ['ID'],
  'PK': ['AF', 'CN', 'IN', 'IR'],
  'PL': ['BY', 'CZ', 'DE', 'LT', 'RU', 'SK', 'UA'],
  'PS': ['IL', 'EG', 'JO'],
  'PT': ['ES'],
  'PY': ['AR', 'BO', 'BR'],
  'QA': ['SA'],
  'RO': ['BG', 'HU', 'MD', 'RS', 'UA'],
  'RS': ['BA', 'BG', 'HR', 'HU', 'XK', 'MK', 'ME', 'RO'],
  'RU': ['AZ', 'BY', 'CN', 'EE', 'FI', 'GE', 'KZ', 'KP', 'LV', 'LT', 'MN', 'NO', 'PL', 'UA'],
  'RW': ['BI', 'CD', 'TZ', 'UG'],
  'SA': ['IQ', 'JO', 'KW', 'OM', 'QA', 'AE', 'YE'],
  'SD': ['CF', 'TD', 'EG', 'ER', 'ET', 'LY', 'SS'],
  'SE': ['FI', 'NO'],
  'SI': ['AT', 'HR', 'IT', 'HU'],
  'SK': ['AT', 'CZ', 'HU', 'PL', 'UA'],
  'SL': ['GN', 'LR'],
  'SM': ['IT'],
  'SN': ['GM', 'GN', 'GW', 'ML', 'MR'],
  'SO': ['DJ', 'ET', 'KE'],
  'SR': ['BR', 'GF', 'GY'],
  'SS': ['CF', 'CD', 'ET', 'KE', 'SD', 'UG'],
  'SV': ['GT', 'HN'],
  'SX': ['MF'],
  'SY': ['IQ', 'IL', 'JO', 'LB', 'TR'],
  'SZ': ['MZ', 'ZA'],
  'TD': ['CM', 'CF', 'LY', 'NE', 'NG', 'SD'],
  'TG': ['BJ', 'BF', 'GH'],
  'TH': ['MM', 'KH', 'LA', 'MY'],
  'TJ': ['AF', 'CN', 'KG', 'UZ'],
  'TL': ['ID'],
  'TM': ['AF', 'IR', 'KZ', 'UZ'],
  'TN': ['DZ', 'LY'],
  'TR': ['AM', 'AZ', 'BG', 'GE', 'GR', 'IR', 'IQ', 'SY'],
  'TZ': ['BI', 'CD', 'KE', 'MW', 'MZ', 'RW', 'UG', 'ZM'],
  'UA': ['BY', 'HU', 'MD', 'PL', 'RO', 'RU', 'SK'],
  'UG': ['CD', 'KE', 'RW', 'SS', 'TZ'],
  'US': ['CA', 'MX'],
  'UY': ['AR', 'BR'],
  'UZ': ['AF', 'KZ', 'KG', 'TJ', 'TM'],
  'VA': ['IT'],
  'VE': ['BR', 'CO', 'GY'],
  'VN': ['KH', 'CN', 'LA'],
  'XK': ['AL', 'MK', 'ME', 'RS'],
  'YE': ['OM', 'SA'],
  'ZA': ['BW', 'LS', 'MZ', 'NA', 'SZ', 'ZW'],
  'ZM': ['AO', 'BW', 'CD', 'MW', 'MZ', 'NA', 'TZ', 'ZW'],
  'ZW': ['BW', 'MZ', 'ZA', 'ZM'],
};
