name: intl_phone_number_input
description: A simple and customizable flutter package for inputting phone number in intl / international format uses Google's libphonenumber.
version: 0.7.1
publish_to: none
homepage: https://github.com/natintosh/intl-phone-number-input

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  libphonenumber:
    git:
      url: https://github.com/kumsumit/flutter-libphonenumber.git
  equatable: ^2.0.5
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

