name: app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  animated_text_kit: ^4.2.1
  auto_size_text:
  connectivity_plus: ^2.3.0 
  cupertino_icons: ^1.0.4
  date_field:
    git: 
      url: https://github.com/sumitsharansatsangi/date_field.git
      ref: 6045ea4e310fd7f0d7120add93e91601ba4a9266  
  dropdown_search:
    git:
      url: https://github.com/sumitsharansatsangi/searchable_dropdown.git
      ref: master   
  omni_datetime_picker: ^0.1.0
  flutter_app_icon_badge: ^2.0.0
  flutter_contacts:
    git:
      url: https://github.com/QuisApp/flutter_contacts.git
      ref: master   
  flutter_native_splash: ^2.1.6
  flutter_quill:
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      ref: bad872c3471b6811e9633ebc0ee50a86b6138570
  flutter_screenutil: ^5.5.2
  flutter_switch: 
    git:
      url: https://github.com/sumitsharansatsangi/FlutterSwitch.git
      ref: master
  flutter_typeahead: ^4.0.0
  flutter: 
    sdk: flutter
  get: ^4.6.5
  get_storage:
    git:
      url: https://github.com/sumitsharansatsangi/get_storage.git
      ref: 0f325e1f4f58f727ee4fce087861d0239259803d
  google_fonts:
  gradient_ui_widgets: ^1.0.2-nullsafety
  internet_connection_checker: ^0.0.1+3
  intl: null
  intl_phone_number_input:
    git:
      url: https://github.com/kumsumit/intl_phone_number_input.git
      ref: 5c6dd1f88ae08f98b91bd775f9d799a0ec5778e7
  math_expressions:
  string_validator:
  objectbox:
  objectbox_flutter_libs:
  open_file:
    git:
      url: https://github.com/sumitsharansatsangi/open_file.git
      ref: gradle-update
  path_provider:
  pdf:
  pdfx:
    git:
      url: https://github.com/sumitsharansatsangi/pdfx.git
      ref: main
  phone_number: 
    git:
      url: https://github.com/sumitsharansatsangi/phone_number.git
      ref: master
  share_plus: 
  speed_up_get: ^0.0.2 
  text_icon:
    git:
      url: https://github.com/sumitsharansatsangi/text_icon.git
      ref: main
  transliteration: ^0.0.6
  unicons: ^2.1.0
  # whatsapp_share2:
  #   git:
  #     url: https://github.com/sumitsharansatsangi/whatsapp_share2.git
  #     ref: dcdd4fed3f4de07d0e747a5085634147604d5826
    

dev_dependencies: 
  build_runner:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  objectbox_generator:  


flutter:
  uses-material-design: true
  assets:
    - assets/data.csv
    - assets/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "45197D"

flutter_native_splash:
  color: "#42a5f5"
  android: true
  ios: true
  image: assets/logo.png
  #   color: "#ccaaff"
  color_dark: "#ab37c8"
  android_12:
    image: assets/logo.png
    image_dark: assets/logo.png