name: intl_phone_number_input
publish_to: none
description: A simple and customizable flutter package for inputting phone number in intl / international format uses Google's libphonenumber.
version: 0.7.3+1
homepage: https://github.com/natintosh/intl-phone-number-input

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  phone_numbers_parser:
    git: https://github.com/sumitsharansatsangi/phone_numbers_parser.git
  circle_flags: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

